# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: pollyttscompass
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
service: api-tts

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:*"  # Permissões totais ao DynamoDB
        - "s3:*"        # Permissões totais ao S3
      Resource: "*"   
  environment:
    BUCKET_NAME: ${env:BUCKET_NAME}
    DYNAMODB_TABLE: ${env:DYNAMODB_TABLE}

functions:
  health:
    handler: handler.health
    events:
      - http:
          path: /
          method: get

  v1Description:
    handler: handler.v1_description
    events:
      - http:
          path: /v1
          method: get

  tts:
    handler: handler.tts
    events:
      - http:
          path: /v1/tts
          method: post

resources:
  Resources:
    TTSTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:DYNAMODB_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:BUCKET_NAME}
